apiVersion: batch/v1
kind: Job
metadata:
  name: volume-init
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: volume-init
          image: {{ .Values.volumeInit.image }}
          command: {{ .Values.volumeInit.command | toJson }}
          volumeMounts:
            - name: oro-app
              mountPath: /mnt/oro_app
      volumes:
        - name: oro-app
          persistentVolumeClaim:
            claimName: pvc-oro-app
