# PVC pour OroCommerce - Approche charts individuels
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-oro-app
  namespace: orocommerce
  labels:
    app: orocommerce
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cache
  namespace: orocommerce
  labels:
    app: orocommerce
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-maintenance
  namespace: orocommerce
  labels:
    app: orocommerce
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-public-storage
  namespace: orocommerce
  labels:
    app: orocommerce
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-private-storage
  namespace: orocommerce
  labels:
    app: orocommerce
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
# PVC pour PostgreSQL (ajout nécessaire)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres-data
  namespace: orocommerce
  labels:
    app: orocommerce
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi