apiVersion: v2
name: monitoring
description: A Helm chart for monitoring OroCommerce with Prometheus and Grafana
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: kube-prometheus-stack
    version: "61.7.2"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled